package config

import "strings"

// DefaultYAML 返回首次运行时生成的示例配置文本。
func DefaultYAML() string { return defaultYAMLTemplate }

// defaultYAMLTemplate 是随二进制分发的默认配置样例。
var defaultYAMLTemplate = strings.Join([]string{
	"# YCFMG 配置文件",
	"# 文档: https://github.com/ycyingchen/ycfmg",
	"# 说明: 环境变量优先级高于本文件（YCFMG_PORT / YCFMG_DATA_DIR / YCFMG_ADMIN_PASSWORD 等）",
	"",
	"server:",
	"  host: 0.0.0.0",
	"  port: 8686",
	"  base_path: \"\"",
	"  trust_proxy: true",
	"  # 多域名绑定：访问者用哪个域名进来，分享链接就用哪个域名生成；",
	"  # 列表第一项作为「首选域名」，用于后台预览与二维码。",
	"  public_urls:",
	"    - http://192.168.1.8:8686",
	"  # tls_cert: /config/cert.pem",
	"  # tls_key:  /config/key.pem",
	"  # readonly: false",
	"",
	"data_dir: /config/ycfmg",
	"",
	"# 被管理的文件库（可挂载多个盘/目录，支持只读）",
	"libraries:",
	"  - name: 照片",
	"    path: /vol1/1000/Photos",
	"    readonly: false",
	"    index: true",
	"  - name: 下载",
	"    path: /vol1/1000/Downloads",
	"    readonly: true",
	"    index: true",
	"",
	"auth:",
	"  username: admin",
	"  # 留空则首次启动随机生成并打印在日志中；账号已初始化后此项不再生效",
	"  password: \"\"",
	"  session_ttl_hours: 1728",
	"  allow_guest: false",
	"",
	"index:",
	"  enabled: true",
	"  scan_interval_minutes: 360",
	"  thumb_sizes: [256, 768]",
	"  auto_tags: true",
	"  hash_tolerance: 6",
	"  max_file_mb: 512",
	"  exclude:",
	"    - .@__thumb",
	"    - \"#recycle\"",
	"    - \"@eaDir\"",
	"    - .git",
	"    - node_modules",
	"    - \"$RECYCLE.BIN\"",
	"    - System Volume Information",
	"",
	"share:",
	"  default_expire_days: 7",
	"  max_items: 2000",
	"  allow_download: true",
	"  brand_name: YCFMG",
	"  brand_subtitle: 文件管理 · 智能图库",
	"",
	"semantic:",
	"  enabled: false",
	"  endpoint: \"\"",
	"  api_key: \"\"",
	"  model: clip-vit-base-patch32",
	"  timeout_sec: 20",
	"",
	"log_level: info",
}, "\n")
